ktor:
  development: false
  application:
    modules:
      - ru.shvets.ktor.ApplicationKt.module
  deployment:
    host: 127.0.0.1
    port: 8080
  datasource:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/me"
    username: "postgres"
    password: "postgres"
jwt:
  secret: "ktor-app"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  issuer: "oleg shvets"
  expiration: 600000